const C=window.PVPVERSE_CONFIG||{};const ready=!!(window.supabase&&C.supabaseUrl&&C.supabasePublishableKey&&!C.supabasePublishableKey.startsWith('YOUR_'));const db=ready?window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey):null;const fallback=[{id:'vip',name:'VIP',price_inr:49,billing_label:'/ month',description:'Your first upgrade.',perks:['VIP chat prefix','Exclusive VIP perks','Priority support'],featured:false,sort_order:1},{id:'vip_plus',name:'VIP+',price_inr:99,billing_label:'/ month',description:'More perks, more presence.',perks:['Everything in VIP','VIP+ cosmetics','Higher priority support'],featured:false,sort_order:2},{id:'mvp',name:'MVP',price_inr:149,billing_label:'/ month',description:'The top donor rank currently available.',perks:['Everything in VIP+','/fly while supported by the server','MVP cosmetics & perks'],featured:true,sort_order:3}];let ranks=[],selected=null;const $=s=>document.querySelector(s);$('#year').textContent=new Date().getFullYear();$('#server').textContent=C.serverAddress||'pvpverse.softhost.fun';for(const id of ['discord','heroDiscord','footDiscord','support'])$('#'+id).href=C.discordUrl||'#';
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function money(n){return '₹'+Number(n).toLocaleString('en-IN')}
function notice(s){$('#notice').textContent=s;$('#notice').classList.remove('hidden')}
function render(){ $('#rankGrid').innerHTML=ranks.map(r=>'<article class="rank '+(r.featured?'featured':'')+'">'+(r.featured?'<span class="badge">BEST VALUE</span>':'')+'<div class="orb">'+esc(r.name[0])+'</div><h3>'+esc(r.name)+'</h3><div class="price">'+money(r.price_inr)+' <small>'+esc(r.billing_label||'/ month')+'</small></div><p class="desc">'+esc(r.description||'')+'</p><ul class="perks">'+(r.perks||[]).map(p=>'<li>'+esc(p)+'</li>').join('')+'</ul><button class="btn '+(r.featured?'primary':'ghost')+' wide" data-buy="'+esc(r.id)+'">Buy '+esc(r.name)+' →</button></article>').join('');document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>openCheckout(b.dataset.buy))}
async function load(){if(!db){ranks=fallback;render();return}const {data,error}=await db.from('rank_products').select('*').eq('active',true).order('sort_order');if(error||!data?.length){ranks=fallback;render();notice('Live catalog unavailable; showing configured defaults.');return}ranks=data;render()}
function handlePaymentReturn(){const state=new URLSearchParams(location.search).get('payment');if(!state)return;const order=localStorage.getItem('pvpverse:last_order');const id=order?JSON.parse(order).id:null;if(state==='success'){notice('Payment verified. Your rank order is now awaiting PvP Verse fulfillment'+(id?' • Order '+id.split('-')[0].toUpperCase():'')+'.');}else if(state==='pending'){notice('Payment is still pending. Do not pay again; contact PvP Verse support if it remains pending.');}else if(state==='failed'){notice('Payment was not completed. You can try checkout again.');}else{notice('We could not verify the payment return. Contact PvP Verse support before paying again.');}history.replaceState({},document.title,location.pathname+location.hash)}
function openCheckout(id){selected=ranks.find(r=>String(r.id)===String(id));if(!selected)return;$('#ctitle').textContent='Buy '+selected.name;$('#summary').textContent=money(selected.price_inr)+' '+(selected.billing_label||'/ month')+' • '+(selected.description||'');$('#form').reset();$('#error').classList.add('hidden');$('#modal').showModal();setTimeout(()=>$('#ign').focus(),50)}
$('#close').onclick=()=>$('#modal').close();
$('#done').onclick=()=>$('#success').classList.add('hidden');
$('#form').onsubmit=async e=>{e.preventDefault();const er=$('#error'),btn=$('#submit');er.classList.add('hidden');const ign=$('#ign').value.trim(),email=$('#email').value.trim(),discord=$('#dname').value.trim(),phone=$('#phone').value.replace(/[s-]/g,'');if(!/^[A-Za-z0-9_]{3,16}$/.test(ign)){er.textContent='Enter a valid Minecraft Java username (3–16 letters, numbers or _).';er.classList.remove('hidden');return}if(!/^+?[0-9]{10,15}$/.test(phone)){er.textContent='Enter a valid phone number.';er.classList.remove('hidden');return}if(!db||!C.functionsUrl){er.textContent='Payment gateway is not configured yet.';er.classList.remove('hidden');return}if(typeof Cashfree!=='function'){er.textContent='Payment checkout could not load. Refresh and try again.';er.classList.remove('hidden');return}btn.disabled=true;btn.textContent='Starting secure checkout…';try{const response=await fetch(C.functionsUrl+'/create-cashfree-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:selected.id,minecraft_ign:ign,discord_username:discord||null,email,customer_phone:phone})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not start payment.');localStorage.setItem('pvpverse:last_order',JSON.stringify({id:data.order_id,rank:selected.name,createdAt:Date.now()}));const cashfree=Cashfree({mode:data.mode==='production'?'production':'sandbox'});await cashfree.checkout({paymentSessionId:data.payment_session_id,redirectTarget:'_self'});}catch(x){console.error(x);er.textContent=x.message||'Could not start payment. Try again.';er.classList.remove('hidden');btn.disabled=false;btn.textContent='Proceed to secure payment'}};
load();handlePaymentReturn();